app:
  timezone: ${APP_TIMEZONE:UTC}
spring:
  application:
    name: discovery-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

server:
  port: ${SERVER_PORT:8761}
  shutdown: graceful

eureka:
  server:
    enable-self-preservation: ${EUREKA_ENABLE_SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL_MS:5000}
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: discovery-service

logging:
  level:
    root: INFO
    com.integrity: INFO
