[versions]
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spotless = "7.0.4"
spotbugs-plugin = "6.1.7"
spotbugs = "4.9.3"
errorprone-plugin = "4.1.0"
errorprone = "2.36.0"
checkstyle = "10.21.4"
pmd = "7.10.0"
jacoco = "0.8.12"
reactor-kafka = "1.3.23"
r2dbc-postgresql = "1.0.7.RELEASE"
jackson = "2.18.2"
otel = "1.46.0"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
spring-boot-starter-data-redis-reactive = { module = "org.springframework.boot:spring-boot-starter-data-redis-reactive" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "otel" }
reactor-kafka = { module = "io.projectreactor.kafka:reactor-kafka", version.ref = "reactor-kafka" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "r2dbc-postgresql" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
reactor-test = { module = "io.projectreactor:reactor-test" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
