[package]
name = "storage"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
config = { path = "../config" }
rusqlite.workspace = true
security = { path = "../security" }
serde_json.workspace = true
telemetry = { path = "../telemetry" }
