spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
        - id: interview
          uri: lb://interview-service
          predicates:
            - Path=/api/v1/interviews/**
      discovery:
        locator:
          enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/interview-integrity

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: api-gateway

logging:
  level:
    root: INFO
    com.interviewintegrity: INFO
