# -----------------------------------------------------------------------------
# Module: secrets-manager
#
# Application secrets (JWT signing key, Redis AUTH, mail credentials, MinIO
# keys, ...) stored in AWS Secrets Manager:
#   * encrypted with the platform KMS key
#   * optional rotation (a shared Lambda regenerates string secrets)
# The module never stores plaintext values in state: values come from the
# caller (usually TF_VAR_* / CI secrets) or are generated by `random_password`.
# -----------------------------------------------------------------------------

variable "name_prefix" {
  type        = string
  description = "Resource name prefix: <project>-<environment>."
}

variable "common_tags" {
  type        = map(string)
  description = "Common platform tags."
  default     = {}
}

variable "kms_key_arn" {
  type        = string
  description = "KMS key ARN encrypting the secrets."
}

variable "secrets" {
  description = <<-EOT
    Map of secret-name -> configuration.
      value      : literal value (overrides random); use TF_VAR_* / CI secrets
      random     : generate a random value when value is empty (default true)
      rotate_days: rotate the secret with the shared rotation Lambda (0 = no rotation)
      description: human readable description
  EOT
  type = map(object({
    value       = optional(string, "")
    random      = optional(bool, true)
    rotate_days = optional(number, 0)
    description = optional(string, "")
  }))
  default = {}
}

resource "random_password" "generated" {
  for_each = { for k, v in var.secrets : k => v if v.value == "" && v.random }

  length      = 48
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "aws_secretsmanager_secret" "this" {
  for_each = var.secrets

  name                    = "${var.name_prefix}/${each.key}"
  description             = each.value.description
  kms_key_id              = var.kms_key_arn
  recovery_window_in_days = 7

  tags = var.common_tags
}

resource "aws_secretsmanager_secret_version" "this" {
  for_each = var.secrets

  secret_id     = aws_secretsmanager_secret.this[each.key].id
  secret_string = each.value.value != "" ? each.value.value : random_password.generated[each.key].result
}

# --- Shared rotation Lambda (string secrets) --------------------------------------

data "archive_file" "rotate" {
  type        = "zip"
  source_file = "${path.module}/rotate/rotate.py"
  output_path = "${path.module}/rotate/rotate.zip"
}

resource "aws_iam_role" "rotate" {
  name = "${var.name_prefix}-secret-rotate"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { Service = "lambda.amazonaws.com" }
        Action    = "sts:AssumeRole"
      }
    ]
  })

  tags = var.common_tags
}

resource "aws_iam_role_policy" "rotate" {
  name = "rotate-secrets"
  role = aws_iam_role.rotate.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret",
          "secretsmanager:PutSecretValue",
          "secretsmanager:UpdateSecretVersionStage",
          "secretsmanager:GetRandomPassword",
        ]
        Resource = values(aws_secretsmanager_secret.this)[*].arn
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_lambda_function" "rotate" {
  function_name = "${var.name_prefix}-secret-rotate"
  role          = aws_iam_role.rotate.arn
  handler       = "rotate.lambda_handler"
  runtime       = "python3.12"
  timeout       = 120
  publish       = true

  filename         = data.archive_file.rotate.output_path
  source_code_hash = data.archive_file.rotate.output_base64sha256

  tags = var.common_tags
}

resource "aws_secretsmanager_secret_rotation" "this" {
  for_each = { for k, v in var.secrets : k => v if v.rotate_days > 0 }

  secret_id           = aws_secretsmanager_secret.this[each.key].id
  rotation_lambda_arn = aws_lambda_function.rotate.arn

  rotation_rules {
    automatically_after_days = each.value.rotate_days
  }
}

output "secret_arns" {
  description = "Map of secret-name -> secret ARN."
  value       = { for k, v in aws_secretsmanager_secret.this : k => v.arn }
}

output "secret_names" {
  description = "Map of secret-name -> secret name."
  value       = { for k, v in aws_secretsmanager_secret.this : k => v.name }
}
