spring:
  application:
    name: desktop-client-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8086
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: desktop-client-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.interviewintegrity: INFO
