package com.integrity.telemetry.repository;

import com.integrity.common.R2dbcBindings;
import com.integrity.telemetry.domain.TelemetrySession;
import com.integrity.telemetry.domain.TelemetrySessionStatus;
import io.r2dbc.spi.Row;
import java.time.Instant;
import java.util.UUID;
import org.springframework.r2dbc.core.DatabaseClient;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Database client backed repository for the {@code telemetry_sessions} table.
 *
 * <p>Explicit SQL keeps writes on the happy path (id generated by the database, version column
 * defaulted) independent of optimistic-lock state, which avoids relying on Spring Data's is-new
 * detection for inserts.
 */
public final class TelemetrySessionRepository {

  private static final String COLUMNS =
      "id, organization_id, interview_id, candidate_id, device_id, client_version, "
          + "status::text AS status, heartbeat_cadence_seconds, started_at, ended_at, "
          + "created_at, updated_at, version";

  private static final String BIND_ORGANIZATION_ID = "organizationId";
  private static final String BIND_STATUS = "status";

  private final DatabaseClient databaseClient;

  /** Creates a repository bound to the given database client. */
  public TelemetrySessionRepository(DatabaseClient databaseClient) {
    this.databaseClient = databaseClient;
  }

  /** Inserts a new session and returns the persisted row. */
  public Mono<TelemetrySession> insert(TelemetrySession session) {
    DatabaseClient.GenericExecuteSpec spec =
        databaseClient
            .sql(
                "INSERT INTO telemetry_sessions "
                    + "(organization_id, interview_id, candidate_id, device_id, client_version, "
                    + " status, heartbeat_cadence_seconds, started_at) "
                    + "VALUES (:organizationId, :interviewId, :candidateId, :deviceId, "
                    + " :clientVersion, :status, :heartbeatCadence, :startedAt) "
                    + "RETURNING "
                    + COLUMNS)
            .bind(BIND_ORGANIZATION_ID, session.getOrganizationId())
            .bind("interviewId", session.getInterviewId())
            .bind(BIND_STATUS, session.getStatus().name())
            .bind("heartbeatCadence", session.getHeartbeatCadenceSeconds())
            .bind("startedAt", session.getStartedAt());
    spec = R2dbcBindings.bindOrNull(spec, "candidateId", session.getCandidateId(), UUID.class);
    spec = R2dbcBindings.bindOrNull(spec, "deviceId", session.getDeviceId(), String.class);
    spec =
        R2dbcBindings.bindOrNull(spec, "clientVersion", session.getClientVersion(), String.class);
    return spec.map((row, metadata) -> map(row)).one();
  }

  /** Inserts a session with a client-managed identifier, ignoring duplicates. */
  public Mono<TelemetrySession> insertWithId(TelemetrySession session) {
    DatabaseClient.GenericExecuteSpec spec =
        databaseClient
            .sql(
                "INSERT INTO telemetry_sessions "
                    + "(id, organization_id, interview_id, candidate_id, device_id, "
                    + " client_version, status, heartbeat_cadence_seconds, started_at) "
                    + "VALUES (:id, :organizationId, :interviewId, :candidateId, :deviceId, "
                    + " :clientVersion, :status, :heartbeatCadence, :startedAt) "
                    + "ON CONFLICT (id) DO NOTHING RETURNING "
                    + COLUMNS)
            .bind("id", session.getId())
            .bind(BIND_ORGANIZATION_ID, session.getOrganizationId())
            .bind("interviewId", session.getInterviewId())
            .bind(BIND_STATUS, session.getStatus().name())
            .bind("heartbeatCadence", session.getHeartbeatCadenceSeconds())
            .bind("startedAt", session.getStartedAt());
    spec = R2dbcBindings.bindOrNull(spec, "candidateId", session.getCandidateId(), UUID.class);
    spec = R2dbcBindings.bindOrNull(spec, "deviceId", session.getDeviceId(), String.class);
    spec =
        R2dbcBindings.bindOrNull(spec, "clientVersion", session.getClientVersion(), String.class);
    return spec.map((row, metadata) -> map(row)).one();
  }

  /** Finds a session by id. */
  public Mono<TelemetrySession> findById(UUID id) {
    return databaseClient
        .sql("SELECT " + COLUMNS + " FROM telemetry_sessions WHERE id = :id")
        .bind("id", id)
        .map((row, metadata) -> map(row))
        .one();
  }

  /** Lists the sessions of an organization, newest first. */
  public Flux<TelemetrySession> listByOrganization(UUID organizationId) {
    return databaseClient
        .sql(
            "SELECT "
                + COLUMNS
                + " FROM telemetry_sessions "
                + "WHERE organization_id = :organizationId ORDER BY started_at DESC")
        .bind(BIND_ORGANIZATION_ID, organizationId)
        .map((row, metadata) -> map(row))
        .all();
  }

  /** Applies a lifecycle transition to a session owned by the organization. */
  public Mono<TelemetrySession> updateStatus(
      UUID id, UUID organizationId, TelemetrySessionStatus status, Instant endedAt) {
    DatabaseClient.GenericExecuteSpec spec =
        databaseClient
            .sql(
                "UPDATE telemetry_sessions SET status = :status, ended_at = :endedAt, "
                    + "updated_at = now() WHERE id = :id AND organization_id = :organizationId "
                    + "RETURNING "
                    + COLUMNS)
            .bind("id", id)
            .bind(BIND_ORGANIZATION_ID, organizationId)
            .bind(BIND_STATUS, status.name());
    return R2dbcBindings.bindOrNull(spec, "endedAt", endedAt, Instant.class)
        .map((row, metadata) -> map(row))
        .one();
  }

  /** Refreshes the client identity of a session owned by the organization. */
  public Mono<TelemetrySession> updateClientInfo(
      UUID id,
      UUID organizationId,
      String deviceId,
      String clientVersion,
      TelemetrySessionStatus status) {
    DatabaseClient.GenericExecuteSpec spec =
        databaseClient
            .sql(
                "UPDATE telemetry_sessions SET device_id = :deviceId, "
                    + "client_version = :clientVersion, status = :status, updated_at = now() "
                    + "WHERE id = :id AND organization_id = :organizationId RETURNING "
                    + COLUMNS)
            .bind("id", id)
            .bind(BIND_ORGANIZATION_ID, organizationId)
            .bind(BIND_STATUS, status.name());
    spec = R2dbcBindings.bindOrNull(spec, "deviceId", deviceId, String.class);
    spec = R2dbcBindings.bindOrNull(spec, "clientVersion", clientVersion, String.class);
    return spec.map((row, metadata) -> map(row)).one();
  }

  private TelemetrySession map(Row row) {
    Integer cadence = row.get("heartbeat_cadence_seconds", Integer.class);
    Long version = row.get("version", Long.class);
    return new TelemetrySession(
        row.get("id", UUID.class),
        row.get("organization_id", UUID.class),
        row.get("interview_id", UUID.class),
        row.get("candidate_id", UUID.class),
        row.get("device_id", String.class),
        row.get("client_version", String.class),
        TelemetrySessionStatus.valueOf(row.get("status", String.class)),
        cadence == null ? 0 : cadence,
        row.get("started_at", Instant.class),
        row.get("ended_at", Instant.class),
        row.get("created_at", Instant.class),
        row.get("updated_at", Instant.class),
        version == null ? 1L : version);
  }
}
